### PR TITLE
allow setting custom logger

### PR DESCRIPTION
**Pull request by szkiba**
Allow setting a custom logger (Logger impl) instead of standard one.

### CODE REVIEW

**Comment by szkiba** [comment]
Hi @pior , could you approve and merge this PR please...
As I see there is a related PR (#17) but it would be cleaner to allow changing the whole Logger implementation to custom one...

**Comment by pior** [comment]
> it would be cleaner to allow changing the whole Logger implementation to custom one...

This is absolutely right, thanks for this PR 👍

**Comment by szkiba** [comment]
Hi @pior , just one other thing :) could you please release it.... (or when are you plan the next release?)

**Comment by pior** [comment]
Done: https://github.com/pior/runnable/releases/tag/v0.9.0

**Comment by szkiba** [comment]
Thanx

Pior Bastida ***@***.***> ezt írta (időpont: 2022. ápr. 14.,
Cs, 1:33):

**Pull request merged**
